# Современные методы анализа данных и машинного обучения, БИ

## НИУ ВШЭ, 2025-26 учебный год

## Групповой проект №5. Deep Learning

## Общая информация

__Дата выдачи:__ 25.05.2026

__Дедлайн по записи в таблицу:__ 4:00 03.06.2026

__Дедлайн по загрузке работ:__ 4:00 15.06.2026

__Защита проекта:__ ~

## Формат выполнения

Групповой проект представляет собой творческое инициативное групповое задание, которое выполняется студентами в командах от 3 до 6 человек. В то же время следует помнить, что чем больше в команде людей, тем выше предъявляются требования в целом к команде, а также к выполняемому ею проекту. Команды разрешается формировать из студентов разных групп.

При оценивании результатов выполнения проекта командой в обязательном порядке проверяется и учитывается в оценке вклад **каждого участника** в общую работу команды. Вследствие этого крайне важно ответственно подойти к выбору сокомандников, распределению обязанностей внутри команды, а также пресечению наличия "мертвых душ" в команде.

При необходимости команда большинством голосов имеет право исключить человека из команды **до загрузки работ** в систему [Anytask](https://anytask.org/), сообщив об этом преподавателю, в случае если такой человек никак не проявлялся в ходе выполнения проекта и являлся как раз таки той самой "мертвой душой". Помните про эту возможность, поскольку наличие "мертвых душ" может негативно повлиять на качество и оценку для всего проекта и, как следствие, в целом для всей команды!

Запись составов команд осуществляется по ссылке в таблице:

https://docs.google.com/spreadsheets/d/16IB8mURLGKoipq0Jld6wOGPMpJbRQ8GCkSZKbIP-XYA/edit?usp=sharing

## Отправка материалов группового проекта

Во избежание использования при выполнении группового проекта генеративных моделей (ChatGPT и так далее) за рамками справочной и образовательной информации (то есть, например, для автоматической генерации кода по одному из этапов) **одному из участников команды** необходимо предварительно загрузить работу в систему [Anytask](https://anytask.org/). Наличие сгенерированного кода или любого другого случая "несанкционированного" использования нейросетей будет считаться плагиатом, и такой проект будет оценен в 0 баллов для всех участников. При отсутствии своевременно загруженных файлов с проектом команде также выставляется 0 за проект.

*Примечание: презентацию проекта загружать необязательно, важно отправить содержательные файлы с кодом и ссылку на репозиторий GitHub.*

## Оценивание и штрафы

Групповой проект оценивается исходя из устной защиты (презентации) командой выполненного ими проекта перед комиссией. Комиссия составляется из преподавателей курса, ассистентов курса, а также приглашенных экспертов из индустрии.

В рамках каждой защиты комиссия выставляет два типа оценок.

Первая оценка — это оценка для всего проекта в целом. Она ставится комиссией, исходя из глубины проработки командой предметной области, сложности применяемых в проекте инструментов, а также прочих аспектов, связанных с содержанием выполняемого в проекте ТЗ. При выставлении этой оценки комиссия ориентируется на критерии, более подробно представленные ниже в разделе "Критерии оценки проекта".

Вторая оценка — это индивидуальная оценка каждого участника команды. Именно эта оценка выставляется впоследствии в ведомость. Индивидуальная оценка участника команды определяется комиссией, исходя из того, насколько участник ориентируется в выполненном командой проекте, как он отвечает на адресованные персонально ему вопросы комиссии, насколько в принципе прослеживается его роль в проекте, а также исходя из других аспектов, связанных с участием конкретного человека в деятельности команды. Индивидуальная оценка не может превосходить оценку команды за проект в целом (первую оценку), однако, в случае когда участник спокойно и корректно отвечает на все адресованные ему вопросы, свободно ориентируется в материале и содержании выполненного проекта, а также когда его роль в работе команды не вызывает сомнений, — в таком случае, индивидуальная оценка участника становится равной оценке для всего проекта (т.е. в идеальном случае — вторая оценка равна первой оценке). Кроме того, в исключительных случаях, при демонстрации участником на защите превосходящих ожидания уровней понимания, участия и вовлечения в рамках проекта, комиссия может своим решением повысить индивидуальную оценку для этого участника на 0,5 или 1 балл относительно общей оценки за проект (первой оценки).

Во избежание субъективности и/или предвзятости оценки тех или иных членов комиссии в отношении тех или иных команд, а также каких-либо иных проявлений неравных условий — распределение команд между комиссиями осуществляется абсолютно рандомно с использованием средств библиотеки Numpy :)) — в качестве рэндом сида выступает дата, в которую производится распределение, например, `np.random.seed(25052026)`.

Обратите, пожалуйста, внимание на то, что бОльшая часть комиссий осуществляет приём проектов в очной форме, однако могут присутствовать и 1-2 комиссии, которые будут работать дистанционно с использованием средств видеосвязи. В случае попадания команды путем случайного распределения в комиссию, работающую в очной форме, *не допускается* какое-либо изменение формата проведения для команды на онлайн-режим, равно как и любые другие перемещения команд между комиссиями (смены комиссий), для сохранения честности и непредвзятости случайного распределения.

Явка студента на защиту проекта является обязательной; вклад студента без его присутствия не оценивается и автоматически является равным нулю. Для дистанционных комиссий дополнительным требованием является обязательное наличие включенной камеры в течение всего времени нахождения в конференции

## Описание задания

В современной бизнес-индустрии использование глубинного обучения приобретает критическое значение. Компании активно внедряют нейронные сети для решения самых разных задач: от анализа структурированных табличных данных до работы с изображениями и текстами. Это позволяет бизнесу принимать более обоснованные решения и оперативно реагировать на изменения рынка.

В данном проекте вы на реальных данных попрактикуетесь в построении и сравнении нейросетевых архитектур для решения двух бизнес-задач разной природы. Первая задача будет связана с табличными данными и решается с помощью полносвязных нейронных сетей. Вторая - с неструктурированными данными: изображениями или текстами, - и решается с помощью более сложных архитектур глубинного обучения. Помимо этого, вы получите опыт организации работы над ML-проектом так, как это принято в индустрии: с версионированием кода, воспроизводимыми экспериментами и сохранением всех артефактов.

Принципиально важно, что обе бизнес-задачи должны быть **содержательно связаны между собой** и **относиться к одной и той же компании или платформе** — таким образом, чтобы вместе они образовывали единое и логически целостное решение для выбранного бизнес-контекста. Проект, в котором две задачи решаются для разных компаний или никак не связаны между собой, оценивается в **0 баллов** для всех участников команды.

### Этапы проекта

Ниже вашему вниманию предлагаются примерные этапы реализации проекта:

- Выбор компании и/или платформы;
- Формулировка двух связанных бизнес-задач, которые могла бы хотеть решить компания/платформа на основе данных: одна на табличных данных, другая на неструктурированных (изображения или текст);
- Обоснование сформулированных бизнес-задач и описание того, как предлагаемое решение вписывается в бизнес-процессы компании;
- Получение необходимых данных путём поиска открытых источников/датасетов, парсинга/работы с API;
- Формулировка задач в терминах глубинного обучения для решения поставленных бизнес-задач;
- Выбор и обоснование архитектур нейронных сетей для каждой из задач;
- Первичная обработка данных;
- Построение, обучение и сравнение нейросетевых архитектур с обязательным логированием экспериментов;
- Получение и агрегация результатов, финальные выводы.

### Требования к проекту

В качестве результата выполнения группового проекта ваша команда должна получить презентацию и защитить её перед комиссией, а также предоставить ссылку на репозиторий GitHub с кодом.

Оформление презентации остаётся полностью на ваше усмотрение, но помните, что результат должен быть релевантен для демонстрации бизнес-заказчику — комиссию, принимающую вашу работу, правильнее всего воспринимать именно в таком качестве. Например, вставлять в презентацию строчки кода или злоупотреблять скринами блокнота не рекомендуется.

С точки зрения концепции выполнения проекта, вам необходимо принять на себя роль дата-инженеров: продумать идеологию получения и извлечения данных; дата-аналитиков: соотнести бизнес-задачу с формулировками на языке данных; и главное, безусловно, — дата-сайентистов: реализовать поставленные задачи с помощью методов глубинного обучения и извлечь полезные инсайты из проделанной работы. А в конце, конечно, презентовать всю эту красоту в понятном виде потенциальному заказчику.

Разумеется, чем сложнее и чем нетривиальнее будет ваша задача, а также чем глубже и чем осмысленнее будут выводы, извлечённые в рамках этой задачи, — тем выше окажется качество вашего проекта и тем выше он будет оценён!

### Полезные замечания и советы

- Графики и визуализации — это очень хорошо — все любят графики
- Следите за тем, чтобы все графики на слайдах можно было прочитать даже без ваших комментариев
- Не нужно делать просто текстовые слайды
- Стройте свой проект исходя из того, что ваша цель — представить полезную информацию для бизнеса
- Любой хороший Data Scientist должен уметь работать в команде, поэтому распределение ваших усилий в проекте остается за вами

## Критерии оценки проекта

Оценка за групповой проект в целом — то есть первая из двух оценок — выставляется по 10-балльной шкале, исходя из 5 критериев. Также комиссия на своё усмотрение может добавить (но не снизить) некоторое количество бонусных баллов за рамками данных критериев.

Каждый из критериев будет перечислен и рассмотрен ниже.

### Критерий 1. Выбор задач и бизнес-обоснование (до 2 баллов)

Данный критерий оценивает, насколько обоснованными и осмысленными и **содержательно связанными** получились две решаемые в проекте бизнес-задачи; насколько полно был осуществлён переход от бизнес-задач к задачам глубинного обучения (насколько в реальности постановка задач соответствует исходной постановке задачи с точки зрения интересов компании); а также насколько корректными, объёмными и прикладными для бизнеса получились выявленные в ходе исследования инсайты.

По данному критерию можно получить **максимальный балл** только при условии, что в презентации представлена схема, иллюстрирующая, как предлагаемое решение вписывается в бизнес-процессы компании: откуда поступают данные, каким образом они обрабатываются, как модель генерирует предсказания и каким образом эти предсказания используются для принятия бизнес-решений. Строгая нотация не обязательна — важна логика и понятность схемы для стороннего наблюдателя.

### Критерий 2. Инструменты извлечения и обработки данных (до 1,5 баллов)

Данный критерий оценивает техническую реализацию процесса сбора данных ручным и автоматизированным образом, использованные средства предобработки, подготовки данных и EDA. В рамках этого критерия будет рассматриваться спектр различных технических инструментов, внедрённых в проект; корректность, эффективность и правильность их применения; а также сложность и новизна алгоритмов, подходов и библиотек, применяемых к данным.

### Критерий 3. Глубинное обучение на табличных данных (до 2 баллов)

Данный критерий оценивает применение полносвязных нейронных сетей для решения бизнес-задачи на табличных данных. В рамках этого критерия будет рассматриваться корректность постановки задачи, осмысленность выбора архитектуры, качество предобработки данных, а также глубина сравнительного анализа различных конфигураций сети.

*__Важно:__ в случае **оценки 0** за этот критерий оценка за весь проект становится равна оценке за этот критерий.*

*По данному критерию можно получить **отличное от нуля количество баллов** только при условии корректного применения полносвязной нейронной сети для решения поставленной задачи на табличных данных.*

*По данному критерию можно получить **1 балл и выше** только при условии осуществления сравнительного анализа различных конфигураций и сложности архитектуры: должно быть рассмотрено не менее трёх вариантов, значимо отличающихся друг от друга — например, по глубине сети, размеру скрытых слоёв, функциям активации, наличию регуляризации. Использование каждой конфигурации, как и подбор гиперпараметров, должны быть подробно описаны и обоснованы; в рамках сравнения должны быть получены и сформулированы явные, значимые выводы о том, как изменение архитектуры влияет на качество решения задачи.*

*По данному критерию можно получить **максимальный балл в 2 балла** только при условии корректного и обоснованного применения архитектурных решений или подходов, не рассматривавшихся в рамках соответствующих лекций и семинаров. Кроме того, **максимальный балл в 2 балла** по данному критерию недостижим без логирования экспериментов в соответствии с требованиями **Критерия 5**. При этом ожидается, что каждая из сравниваемых конфигураций залогирована отдельным запуском с сохранением параметров архитектуры и обучения, метрик качества, а также артефакта обученной модели, позволяющего воспроизвести её предсказания без повторного обучения.*

### Критерий 4. Глубинное обучение на неструктурированных данных  (до 3 баллов)

Данный критерий оценивает применение методов глубинного обучения для решения бизнес-задачи на неструктурированных данных: изображениях или текстах. В рамках этого критерия будет рассматриваться спектр различных технических инструментов, внедрённых в проект; корректность, эффективность и правильность их применения; а также сложность и новизна алгоритмов, подходов и библиотек, применяемых к данным. Кроме того, будет оценен сравнительный анализ архитектур нейронных сетей, использованных в решении.

*__Важно:__ в случае **оценки 0** за этот критерий оценка за весь проект становится равна оценке за этот критерий.*

*По данному критерию можно получить **отличное от нуля количество баллов** только при условии использования в проекте сверточных нейронных сетей, рекуррентных нейронных сетей или же более сложных архитектур глубоких нейронных сетей.*

*По данному критерию можно получить **2 балла** только при условии осуществления сравнительного анализа эффективности различных архитектур нейронных сетей внутри вашего проекта на одних и тех же данных. Самих архитектур должно быть не менее трёх; они должны значимо и осмысленно друг от друга отличаться; их использование, как и настройка гиперпараметров, должны быть подробно описаны и обоснованы. Кроме того, в рамках сравнительного анализа должны быть получены и сформулированы явные, значимые выводы о сравнительной эффективности той или иной архитектуры.*

*По данному критерию можно получить **максимальный балл в 3 балла** только при условии корректного и обоснованного применения инструментов/подходов/библиотек для построения моделей, не рассматривавшихся в рамках соответствующих лекций и семинаров. Кроме того, **максимальный балл в 3 балла** по данному критерию недостижим без логирования экспериментов в соответствии с требованиями **Критерия 5**. При этом ожидается, что каждая из сравниваемых архитектур залогирована отдельным запуском с сохранением параметров архитектуры и обучения, метрик качества в разрезе эпох, а также артефакта обученной модели, позволяющего воспроизвести её предсказания без повторного обучения.*

### Критерий 5. Инструменты промышленной разработки (до 1,5 баллов)

Данный критерий оценивает, насколько грамотно и профессионально команда организовала процесс совместной разработки и обеспечила воспроизводимость своих экспериментов. В рамках этого критерия рассматриваются две составляющие: оформление репозитория GitHub и логирование экспериментов.

*По данному критерию можно получить **0,5 балла** при выполнении всех следующих требований к репозиторию GitHub:*

- наличие файла `README.md` с описанием проекта, используемых данных и структуры репозитория — после прочтения этого файла у стороннего человека не должно остаться вопросов о том, что делает проект и как в нём разобраться;
- наличие файла `.gitignore`;
- осмысленная структура репозитория: код организован по директориям, понятно, где лежат данные, где модели, где ноутбуки;
- коммиты делаются осмысленно и регулярно по ходу работы над проектом, с понятными комментариями — по истории репозитория должно быть видно, что команда работала совместно на протяжении всего времени, а не залила всё в одном коммите накануне дедлайна.

*По данному критерию можно получить **1 балл** при дополнительном выполнении следующего условия: все эксперименты с моделями — как на табличных, так и на неструктурированных данных — залогированы с использованием специализированного инструмента логирования экспериментов (например, MLflow, Weights & Biases, ClearML, DagsHub или аналогичного). Каждый эксперимент должен быть зафиксирован отдельным запуском и содержать: параметры модели и обучения, метрики качества — для табличных задач в целом по выборке, для задач на неструктурированных данных дополнительно в разрезе эпох, — а также артефакт обученной модели, позволяющий воспроизвести её предсказания без повторного обучения. Хранение файлов моделей исключительно напрямую в репозитории без привязки к системе логирования не засчитывается.*

*По данному критерию можно получить **1,5 балла** при дополнительном выполнении следующего условия: в системе логирования сохранены также данные, использованные при обучении и валидации моделей, — таким образом, чтобы любой эксперимент можно было полностью воспроизвести, имея доступ только к системе логирования, без необходимости искать данные отдельно.*

In [3]:
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score
from sklearn.compose import ColumnTransformer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.svm import LinearSVC
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
d = pd.read_json('Cell_Phones_and_Accessories_5.json', lines=True)
d.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime
0,A30TL5EWN6DFXT,120401325X,christina,"[0, 0]",They look good and stick good! I just don't li...,4,Looks Good,1400630400,"05 21, 2014"
1,ASY55RVNIL0UD,120401325X,emily l.,"[0, 0]",These stickers work like the review says they ...,5,Really great product.,1389657600,"01 14, 2014"
2,A2TMXE2AFO7ONB,120401325X,Erica,"[0, 0]",These are awesome and make my phone look so st...,5,LOVE LOVE LOVE,1403740800,"06 26, 2014"
3,AWJ0WZQYMYFQ4,120401325X,JM,"[4, 4]",Item arrived in great time and was in perfect ...,4,Cute!,1382313600,"10 21, 2013"
4,ATX7CZYFXI1KW,120401325X,patrice m rogoza,"[2, 3]","awesome! stays on, and looks great. can be use...",5,leopard home button sticker for iphone 4s,1359849600,"02 3, 2013"

In [5]:
d.shape

(194439, 9)

In [6]:
d['overall'].value_counts()

overall
5    108664
4     39993
3     21439
1     13279
2     11064
Name: count, dtype: int64

In [7]:
d = d.dropna(subset=['reviewText', 'overall'])
d = d.drop_duplicates(subset=['reviewerID', 'asin', 'unixReviewTime'])

In [8]:
d['full_text'] = d['summary'].fillna('') + " " + d['reviewText']

In [9]:
d.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,full_text
0,A30TL5EWN6DFXT,120401325X,christina,"[0, 0]",They look good and stick good! I just don't li...,4,Looks Good,1400630400,"05 21, 2014",Looks Good They look good and stick good! I ju...
1,ASY55RVNIL0UD,120401325X,emily l.,"[0, 0]",These stickers work like the review says they ...,5,Really great product.,1389657600,"01 14, 2014",Really great product. These stickers work like...
2,A2TMXE2AFO7ONB,120401325X,Erica,"[0, 0]",These are awesome and make my phone look so st...,5,LOVE LOVE LOVE,1403740800,"06 26, 2014",LOVE LOVE LOVE These are awesome and make my p...
3,AWJ0WZQYMYFQ4,120401325X,JM,"[4, 4]",Item arrived in great time and was in perfect ...,4,Cute!,1382313600,"10 21, 2013",Cute! Item arrived in great time and was in pe...
4,ATX7CZYFXI1KW,120401325X,patrice m rogoza,"[2, 3]","awesome! stays on, and looks great. can be use...",5,leopard home button sticker for iphone 4s,1359849600,"02 3, 2013",leopard home button sticker for iphone 4s awes...

In [10]:
nltk.download(['stopwords', 'wordnet', 'punkt'])

stop_slova = set(stopwords.words('english'))
lemma = WordNetLemmatizer()

def menyaem_text(t):
    t = t.lower()
    t = re.sub(r'[^a-z\s]', ' ', t)
    t = re.sub(r'\s+', ' ', t)
    t = t.strip()

    tks = t.split()
    temp = []
    for i in tks:
        if i not in stop_slova and len(i) >= 2:
            temp.append(lemma.lemmatize(i))

    return " ".join(temp)

d['clean_text'] = d['full_text'].apply(menyaem_text)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

In [11]:
d.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,full_text,clean_text
0,A30TL5EWN6DFXT,120401325X,christina,"[0, 0]",They look good and stick good! I just don't li...,4,Looks Good,1400630400,"05 21, 2014",Looks Good They look good and stick good! I ju...,look good look good stick good like rounded sh...
1,ASY55RVNIL0UD,120401325X,emily l.,"[0, 0]",These stickers work like the review says they ...,5,Really great product.,1389657600,"01 14, 2014",Really great product. These stickers work like...,really great product sticker work like review ...
2,A2TMXE2AFO7ONB,120401325X,Erica,"[0, 0]",These are awesome and make my phone look so st...,5,LOVE LOVE LOVE,1403740800,"06 26, 2014",LOVE LOVE LOVE These are awesome and make my p...,love love love awesome make phone look stylish...
3,AWJ0WZQYMYFQ4,120401325X,JM,"[4, 4]",Item arrived in great time and was in perfect ...,4,Cute!,1382313600,"10 21, 2013",Cute! Item arrived in great time and was in pe...,cute item arrived great time perfect condition...
4,ATX7CZYFXI1KW,120401325X,patrice m rogoza,"[2, 3]","awesome! stays on, and looks great. can be use...",5,leopard home button sticker for iphone 4s,1359849600,"02 3, 2013",leopard home button sticker for iphone 4s awes...,leopard home button sticker iphone awesome sta...

In [12]:
d[['like', 'dislike']] = pd.DataFrame(d['helpful'].tolist(), index=d.index)

In [13]:
d.head()

,reviewerID,asin,reviewerName,helpful,reviewText,overall,summary,unixReviewTime,reviewTime,full_text,clean_text,like,dislike
0,A30TL5EWN6DFXT,120401325X,christina,"[0, 0]",They look good and stick good! I just don't li...,4,Looks Good,1400630400,"05 21, 2014",Looks Good They look good and stick good! I ju...,look good look good stick good like rounded sh...,0,0
1,ASY55RVNIL0UD,120401325X,emily l.,"[0, 0]",These stickers work like the review says they ...,5,Really great product.,1389657600,"01 14, 2014",Really great product. These stickers work like...,really great product sticker work like review ...,0,0
2,A2TMXE2AFO7ONB,120401325X,Erica,"[0, 0]",These are awesome and make my phone look so st...,5,LOVE LOVE LOVE,1403740800,"06 26, 2014",LOVE LOVE LOVE These are awesome and make my p...,love love love awesome make phone look stylish...,0,0
3,AWJ0WZQYMYFQ4,120401325X,JM,"[4, 4]",Item arrived in great time and was in perfect ...,4,Cute!,1382313600,"10 21, 2013",Cute! Item arrived in great time and was in pe...,cute item arrived great time perfect condition...,4,4
4,ATX7CZYFXI1KW,120401325X,patrice m rogoza,"[2, 3]","awesome! stays on, and looks great. can be use...",5,leopard home button sticker for iphone 4s,1359849600,"02 3, 2013",leopard home button sticker for iphone 4s awes...,leopard home button sticker iphone awesome sta...,2,3

In [14]:
d = d[['clean_text', 'overall', 'like', 'dislike']]

In [15]:
d = d.dropna(subset=['clean_text', 'overall', 'like', 'dislike'])

In [16]:
y = d['overall'].astype(int)
X = d[['clean_text', 'like', 'dislike']]

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=67
)

In [17]:
preprocessor = ColumnTransformer(
    transformers=[
        ('text', TfidfVectorizer(max_features=4500, min_df=5, sublinear_tf=True, ngram_range=(1, 2)), 'clean_text'),
        ('num', MinMaxScaler(), ['like', 'dislike'])
    ]
)


X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

In [18]:
X_train.shape

(155551, 4502)

In [19]:
!pip install mlflow

Collecting mlflow
  Downloading mlflow-3.13.0-py3-none-any.whl.metadata (49 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.4/49.4 kB 3.6 MB/s eta 0:00:00
Collecting mlflow-skinny==3.13.0 (from mlflow)
  Downloading mlflow_skinny-3.13.0-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.7 MB/s eta 0:00:00
Collecting mlflow-tracing==3.13.0 (from mlflow)
  Downloading mlflow_tracing-3.13.0-py3-none-any.whl.metadata (19 kB)
Collecting Flask-CORS<7 (from mlflow)
  Downloading flask_cors-6.0.5-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: Flask<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.1.3)
Requirement already satisfied: aiohttp<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.14.1)
Requirement already satisfied: alembic!=1.10.0,<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.18.4)
Requirement already satisfied: cryptography<49,>=43.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (48.0.1)
Collecting docker<8,>=4.0.0 (from mlflow)
  Downloading docker-7.1.0-py3-none-any.whl.metadata (3.8 kB)
Collecting graphene<4 (from mlflow)
  Downloading graphene-3.4.3-py2.py3-none-any.whl.metadata (6.9 kB)
Collecting gunicorn<27 (from mlflow)
  Downloading gunicorn-26.0.0-py3-none-any.whl.metadata (5.4 kB)
Collecting huey<4,>=2.5.4 (from mlflow)
  Downloading huey-3.0.3-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: matplotlib<4 in /usr/local/lib/python3.12/dist-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.2)
Requirement already satisfied: pandas<3 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.2.2)
Requirement already satisfied: pyarrow<25,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (18.1.0)
Requirement already satisfied: scikit-learn<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.6.1)
Requirement already satisfied: scipy<2 in /usr/local/lib/python3.12/dist-packages (from mlflow) (1.16.3)
Collecting skops<1 (from mlflow)
  Downloading skops-0.14.0-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow) (2.0.50)
Requirement already satisfied: cachetools<8,>=5.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (8.4.1)
Requirement already satisfied: cloudpickle<4 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.2)
Collecting databricks-sdk<1,>=0.20.0 (from mlflow-skinny==3.13.0->mlflow)
  Downloading databricks_sdk-0.117.0-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.5/43.5 kB 3.0 MB/s eta 0:00:00
Requirement already satisfied: fastapi<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.136.3)
Requirement already satisfied: gitpython<4,>=3.1.9 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (3.1.50)
Requirement already satisfied: importlib_metadata!=4.7.0,<10,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (8.7.1)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.38.0)
Requirement already satisfied: packaging<27 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (26.2)
Requirement already satisfied: protobuf<8,>=3.12.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (5.29.6)
Requirement already satisfied: pydantic<3,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (2.12.3)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (1.2.2)
Requirement already satisfied: pyyaml<7,>=5.1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (6.0.3)
Requirement already satisfied: requests<3,>=2.17.3 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (2.32.4)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.5.5)
Requirement already satisfied: starlette<2 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.52.1)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in /usr/local/lib/python3.12/dist-packages (from mlflow-skinny==3.13.0->mlflow) (0.49.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4->mlflow) (1.24.2)
Requirement already satisfied: Mako in /usr/local/lib/python3.12/dist-packages (from alembic!=1.10.0,<2->mlflow) (1.3.12)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from cryptography<49,>=43.0.0->mlflow) (2.0.0)
Requirement already satisfied: urllib3>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from docker<8,>=4.0.0->mlflow) (2.5.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.0.3)
Requirement already satisfied: werkzeug>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from Flask<4->mlflow) (3.1.8)
Collecting graphql-core<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_core-3.2.11-py3-none-any.whl.metadata (11 kB)
Collecting graphql-relay<3.3,>=3.1 (from graphene<4->mlflow)
  Downloading graphql_relay-3.2.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in /usr/local/lib/python3.12/dist-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<4->mlflow) (3.3.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3->mlflow) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /usr/local/lib/python3.12/dist-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.5.1)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->cryptography<49,>=43.0.0->mlflow) (3.0)
Requirement already satisfied: google-auth~=2.0 in /usr/local/lib/python3.12/dist-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (2.47.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1->mlflow-skinny==3.13.0->mlflow) (0.0.4)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (4.0.12)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib_metadata!=4.7.0,<10,>=3.7.0->mlflow-skinny==3.13.0->mlflow) (4.1.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.59b0 in /usr/local/lib/python3.12/dist-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.13.0->mlflow) (0.59b0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prettytable>=3.9->skops<1->mlflow) (0.8.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.13.0->mlflow) (2.41.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (3.18)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.17.3->mlflow-skinny==3.13.0->mlflow) (2026.5.20)
Requirement already satisfied: anyio<5,>=3.6.2 in /usr/local/lib/python3.12/dist-packages (from starlette<2->mlflow-skinny==3.13.0->mlflow) (4.13.0)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.12/dist-packages (from uvicorn<1->mlflow-skinny==3.13.0->mlflow) (0.16.0)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.13.0->mlflow) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (4.9.1)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.13.0->mlflow) (0.6.3)
Downloading mlflow-3.13.0-py3-none-any.whl (10.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 103.8 MB/s eta 0:00:00
Downloading mlflow_skinny-3.13.0-py3-none-any.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 115.9 MB/s eta 0:00:00
Downloading mlflow_tracing-3.13.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 69.9 MB/s eta 0:00:00
Downloading docker-7.1.0-py3-none-any.whl (147 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.8/147.8 kB 12.8 MB/s eta 0:00:00
Downloading flask_cors-6.0.5-py3-none-any.whl (16 kB)
Downloading graphene-3.4.3-py2.py3-none-any.whl (114 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.9/114.9 kB 10.6 MB/s eta 0:00:00
Downloading gunicorn-26.0.0-py3-none-any.whl (212 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.0/212.0 kB 22.4 MB/s eta 0:00:00
Downloading huey-3.0.3-py3-none-any.whl (94 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.9/94.9 kB 9.0 MB/s eta 0:00:00
Downloading skops-0.14.0-py3-none-any.whl (132 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.2/132.2 kB 12.8 MB/s eta 0:00:00
Downloading databricks_sdk-0.117.0-py3-none-any.whl (936 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 936.9/936.9 kB 51.1 MB/s eta 0:00:00
Downloading graphql_core-3.2.11-py3-none-any.whl (214 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 214.9/214.9 kB 15.2 MB/s eta 0:00:00
Downloading graphql_relay-3.2.0-py3-none-any.whl (16 kB)
Installing collected packages: huey, gunicorn, graphql-core, graphql-relay, docker, skops, graphene, Flask-CORS, databricks-sdk, mlflow-tracing, mlflow-skinny, mlflow
Successfully installed Flask-CORS-6.0.5 databricks-sdk-0.117.0 docker-7.1.0 graphene-3.4.3 graphql-core-3.2.11 graphql-relay-3.2.0 gunicorn-26.0.0 huey-3.0.3 mlflow-3.13.0 mlflow-skinny-3.13.0 mlflow-tracing-3.13.0 skops-0.14.0

In [20]:
import mlflow
import mlflow.sklearn

mlflow.sklearn.autolog()

with mlflow.start_run():
    model = LinearSVC(dual="auto", class_weight="balanced", random_state=67)

    model.fit(X_train, y_train)

    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    print(accuracy)

    mlflow.log_metric("test_accuracy", accuracy)

2026/06/15 19:42:59 INFO mlflow.store.db.utils: Creating initial MLflow database tables...
2026/06/15 19:42:59 INFO mlflow.store.db.utils: Updating database tables
2026/06/15 19:43:22 WARNING mlflow.sklearn: Failed to log training dataset information to MLflow Tracking. Reason: 'Series' object has no attribute 'flatten'
2026/06/15 19:43:58 WARNING mlflow.sklearn: Saving scikit-learn models in the pickle or cloudpickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is the 'skops' format. For more information, see: https://scikit-learn.org/stable/model_persistence.html

0.6511263114585476

In [21]:
!pip install torch==2.2.2 torchtext==0.17.2 torchaudio==2.2.2 torchvision==0.17.2 torchdata==0.7.1 torchtune --quiet
!pip install portalocker==2.8.2 --quiet
!pip install numpy==1.26.4 --quiet

WARNING: huggingface-hub 1.18.0 does not provide the extra 'hf-transfer'
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.5/755.5 MB 1.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 62.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 49.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.9/6.9 MB 75.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 184.4/184.4 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 67.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 34.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 50.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 764.0 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 14.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 7.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 7.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 810.3/810.3 kB 54.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 39.7/39.7 MB 17.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 5.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 107.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
opencv-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.

In [22]:
d = d[d['clean_text'].fillna('').str.strip().str.len() > 0]

data = list(zip(d['overall'], d['clean_text']))

In [23]:
import torch
print(f"Версия Torch: {torch.__version__}")
print(f"CUDA доступна: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"Видеокарта: {torch.cuda.get_device_name(0)}")

Версия Torch: 2.2.2+cu121
CUDA доступна: False

In [24]:
from torchtext.data.utils import get_tokenizer


# загрузим базовый англоязычный basic_english токенизатор с помощью get_tokenizer
tokenizer = get_tokenizer('basic_english')

In [25]:
from torchtext.vocab import build_vocab_from_iterator


def yield_tokens(data_iter):
    # итерируясь по данным, токенизируем текст в каждом примере в датасете
    for text in data_iter:
        yield tokenizer(str(text))


# добавим в словарь специальные токены для паддинга и для out-of-vocabulary слов
PAD_TOKEN = "<pad>"
UNK_TOKEN = "<unk>"
# выберем максимальную длину последовтаельности
MAX_LENGTH = 128
# зададим размер батча
BATCH_SIZE = 64

# а теперь воспользуемся готовой функцией `build_vocab_from_iterator`
# для того, чтобы собрать словарь токенов из представленого
# итератора yield_tokens(train_iter) по текстам обучающей выборки,
# добавим специальные токены [UNK_TOKEN, PAD_TOKEN] с помощью аргумента specials,
custom_vocab = build_vocab_from_iterator(yield_tokens(d['clean_text']),
                                         specials=[UNK_TOKEN, PAD_TOKEN])
# причем специальному токену для out-of-vocabulary слов назначим
# специальный индекс с помощью метода set_default_index
custom_vocab.set_default_index(custom_vocab[UNK_TOKEN])

In [26]:
custom_vocab.__contains__("penis")

True

In [27]:
custom_vocab.__len__()

72826

In [28]:
custom_vocab.lookup_indices(tokens=["kitty", "jerk", "rose"])

[2058, 8007, 4293]

In [29]:
vocab_tokenizer_pipeline = lambda x: custom_vocab(tokenizer(x))[:MAX_LENGTH]

In [30]:
vocab_tokenizer_pipeline('cat was here')

[2534, 0, 8852]

In [31]:
import torch


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu

In [32]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found

In [33]:
label_pipeline = lambda x: int(x) - 1

In [34]:
vocab_tokenizer_pipeline('cat was here')

[2534, 0, 8852]

In [35]:
label_pipeline(1), label_pipeline(2)

(0, 1)

In [36]:
from torch.utils.data import DataLoader
from torchtext.transforms import ToTensor


def collate_batch(batch):
    """Функция collate_fn нужна DataLoader для того, чтоыб преобразовывать
    получаемый на вход лист примеров (батч в виде листа исходных данных)
    в мини-батч, представляющий из себя тензор.

    Возвращает:
    - label_list - метки классов в целочисленном виде, тензор на девайсе,
    - text_list - токенизированные и проиндексированные тексты, тензор на девайсе,
    - lengths - длины текстов в токенах, тензор на cpu
                (используется nn.utils.rnn.pack_padded_sequence)
    """
    label_list, text_list, lengths = [], [], []
    for (_label, _text) in batch:
        # добавим в список label_list преобразованный с помощью
        # label_pipeline лейбл
        label_list.append(label_pipeline(_label))
        # добавим в список text_list преобразованный с помощью
        # vocab_tokenizer_pipeline текст
        text_list.append(vocab_tokenizer_pipeline(_text))
        # добавим в список lengths длину токенизированного текста
        lengths.append(torch.tensor(len(vocab_tokenizer_pipeline(_text)),
                                    dtype=torch.int64))

    # преобразуем label_list в torch.tensor с целочисленными значениями
    label_list = torch.tensor(label_list, dtype=torch.int64)
    # преобразуем lengths в torch.tensor с целочисленными значениями
    lengths = torch.tensor(lengths, dtype=torch.int64)
    # преобразуем text_list в тензор с помощью ToTensor,
    # задав значение для padding-а custom_vocab[PAD_TOKEN],
    # чтобы тексты были все единой длины - максимальной в батче.
    # при этом помним, что в пайплайне мы уже ограничили максимальную длину
    text_list = ToTensor(padding_value=custom_vocab[PAD_TOKEN]).forward(text_list)
    return label_list.to(device), text_list.to(device), lengths


# снова создадим итератор по обучающей выборке IMDB
train_iter = list(zip(d['overall'], d['clean_text']))
# Создадим DataLoader на основе train_iter,
# задав BATCH_SIZE в качестве значения batch_size,
# определим shuffle в значении False,
# задав collate_batch в качестве collate_fn
dataloader = DataLoader(train_iter,
                        batch_size=BATCH_SIZE,
                        shuffle=False,
                        collate_fn=collate_batch)

In [37]:
for idx, (label, text, lengths) in enumerate(dataloader):
    # метки класса - это целочисленные индексы в списке классов
    print(label)
    # тексты - это целочисленные индексы токенов текста в словаре токенов
    print(text)
    # длины - это целочисленные длины в токенах каждого примера
    # (не более `MAX_LENGTH`, так как мы ограничили максимальную длину еще
    # в пайплайне обработки текстов)
    print(lengths)

    # все длины должны быть равны размеру батча
    print(len(label))
    print(len(text))
    print(len(lengths))
    break

tensor([3, 4, 4, 3, 4, 2, 4, 0, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 0, 4, 4, 2, 3,
        3, 4, 1, 3, 1, 3, 4, 4, 0, 4, 3, 1, 3, 4, 4, 3, 1, 4, 4, 3, 1, 4, 0, 4,
        3, 3, 3, 4, 4, 3, 4, 2, 4, 4, 3, 3, 4, 4, 3, 1])
tensor([[ 27,   7,  27,  ...,   1,   1,   1],
        [ 23,   4,  18,  ...,   1,   1,   1],
        [ 22,  22,  22,  ...,   1,   1,   1],
        ...,
        [ 43, 255, 189,  ...,   1,   1,   1],
        [249, 574,  38,  ...,   1,   1,   1],
        [391,  56, 391,  ...,   1,   1,   1]])
tensor([ 18,  16,  18,  29,  18,  13,  13,   9,  29,  21,   9,  34,  26, 108,
         19,  13,  25,  19,  45,  12,  17,  11,  12,  17,  24,  16,   9,  40,
          6,  12,  23,  14,  27,  12,  15,  12,  18,  23,   8,  40,  19,  20,
         18,  20, 128,  19,  26,  17,  19,   9,  21,  82,  20,  19,  11,  18,
         33,  12,  13,  15,  12,  25,  17,  26])
64
64
64

In [38]:
from torch import nn


class BiLSTMClassificationModel(nn.Module):

    def __init__(self, vocab_size, embed_dim, hidden_dim, num_classes, pad_idx,
                 bidirectional=True, dropout=0.1):
        super().__init__()
        # слой обучаемых векторных представлений nn.Embedding
        # с заданным индексом паддинга pad_idx в качестве аргумента padding_idx,
        # с заданным размером представлений embed_dim,
        # с заданным размером словаря vocab_size и
        # без изначальной инициализации
        self.embedding = nn.Embedding(vocab_size, embed_dim,
                                      padding_idx = pad_idx)
        # слой nn.LSTM с заданным значением dropout, получающий на вход
        # вектора размерности  embed_dim и возвращающий вектора
        # скрытой размерности hidden_dim,
        # также зададим bidirectional в качестве аргумента bidirectional
        self.bilstm = nn.LSTM(embed_dim, hidden_dim,
                              bidirectional=bidirectional,
                              dropout=dropout, batch_first=True)
        # линейный слой nn.Linear,
        # преобразующий вектора размерности hidden_dim * 2
        # (так как используется bidirectional LSTM) в hidden_dim
        self.fc1 = nn.Linear(hidden_dim * 2, hidden_dim)
        # линейный слой nn.Linear,
        # преобразующий вектора размерности hidden_dim
        # в размерность числа классов num_classes
        self.fc2 = nn.Linear(hidden_dim, num_classes)
        # слой nn.Dropout с заданной величиной dropout
        #  для использования - он не имеет весов, поэтому можно
        # задать один слой и использовать его в нескольких местах в сети
        self.dropout = nn.Dropout(dropout)

    def forward(self, text, text_lengths):
        # пропустим полученные на вход тексты через слой self.embedding
        embedded = self.embedding(text)
        # преобразуем векторные представления последовательностей
        # с помощью специальной функции в формат, подходящий для LSTM
        # https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pack_padded_sequence.html?highlight=pack_padded_sequence#torch.nn.utils.rnn.pack_padded_sequence
        packed_embedded = nn.utils.rnn.pack_padded_sequence(
            embedded, text_lengths, batch_first=True, enforce_sorted=False)

        # пропустим последовательность через нашу self.bilstm
        packed_output, (hidden, cell) = self.bilstm(packed_embedded)
        # пропустим скрытые представлния через слой self.dropout
        hidden = self.dropout(torch.cat((hidden[-2,:,:], hidden[-1,:,:]),
                                        dim = 1))
        # пропустим полученные скрытые представления через слой self.fc1
        output = self.fc1(hidden)
        # пропустим полученные скрытые представления через слой self.fc2
        output = self.fc2(output)
        # пропустим полученные скрытые представления через self.dropout
        output = self.dropout(output)
        return output

In [39]:



num_classes =  5
vocab_size = custom_vocab.__len__()

# инициализируем нашу модель BiLSTMClassificationModel,
# передав необходимые параметры:
# размер словаря,
# размер векторных представлений,
# размер скрытого пространства,
# число классов,
# индекс паддинга
# параметр, будет ли модаль двунаправиленной,
# значение дропаут,
# а также перенесем нашу модель на девайс
model = BiLSTMClassificationModel(
    vocab_size,
    embed_dim=64,
    hidden_dim=128,
    num_classes=num_classes,
    pad_idx=custom_vocab[PAD_TOKEN],
    bidirectional=True,
    dropout=0.1
).to(device)

/usr/local/lib/python3.12/dist-packages/torch/nn/modules/rnn.py:83: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.1 and num_layers=1
  warnings.warn("dropout option adds dropout after all but last "

In [40]:
import time


def train(dataloader, epoch, optimizer, criterion):
    # обязательно переводим модель в режим обучения с помощью метода train()
    model.train()
    total_acc, total_count = 0, 0
    # интервал логгирования в числе батчей
    log_interval = 100
    start_time = time.time()

    # итерируемся батчами по заданном даталоадеру
    for idx, (label, text, lengths) in enumerate(dataloader):
        # обнуляем градиенты с помощью метода zero_grad
        optimizer.zero_grad()
        # предсказываем распределение вероятностей по классам,
        # передавай в модель text и lengths
        predicted_label = model(text, lengths)
        # подсчитываем лосс с помощью criterion,
        # вычисляемого на основе predicted_label и label
        loss = criterion(predicted_label, label)
        # обратное распространение ошибки с помощью метода backward()
        loss.backward()
        # ограничиваем норму градиентов с помощью метода
        # torch.nn.utils.clip_grad_norm_, в который передаются
        # параметры модели model.parameters() и макс. значение нормы 0.1

        torch.nn.utils.clip_grad_norm_(model.parameters(), 0.1)

        # делаем шаг оптимизатора, то есть обновляем веса модели,
        # с помощью метода step()
        optimizer.step()
        # подсчитываем точность на батче
        total_acc += (predicted_label.argmax(1) == label).sum().item()
        # подсчитываем число примеров для усреднения точности
        total_count += label.size(0)

        if idx % log_interval == 0 and idx > 0:
            # если пришло время -- логгируем
            elapsed = time.time() - start_time
            print('| epoch {:3d} | {:5d}/{:5d} batches '
                  '| accuracy {:8.3f}'.format(epoch, idx, len(dataloader),
                                              total_acc/total_count))
            total_acc, total_count = 0, 0
            start_time = time.time()

def evaluate(dataloader, criterion):
    # обязательно переводим модель в режим инференса (эвалюации)
    # с помощью метода eval()
    model.eval()
    total_acc, total_count = 0, 0

    # эвалюация не должна обновлять градиенты модели
    with torch.no_grad():
      # итерируемся батчами по заданному даталоадеру
        for idx, (label, text, lengths) in enumerate(dataloader):
            # предсказываем распределение вероятностей по классам,
            # передавай в модель text и lengths
            predicted_label = model(text, lengths)
            # подсчитываем лосс с помощью criterion,
            # вычисляемого на основе predicted_label и label
            loss = criterion(predicted_label, label)
            # предсказываем метки классов и считаем точность
            total_acc += (predicted_label.argmax(1) == label).sum().item()
            # подсчитываем число примеров для усреднения точности
            total_count += label.size(0)
    return total_acc/total_count

In [41]:
from torch.utils.data.dataset import random_split
from torchtext.data.functional import to_map_style_dataset


data = list(zip(d['overall'], d['clean_text']))
ts = int(len(data) * 0.8)
test_size = len(data) - ts
train_data_split, test_dataset = random_split(data, [ts, test_size])
k = int(len(train_data_split) * 0.9)
split_train_, split_valid_ = random_split(train_data_split, [k, len(train_data_split) - k])

# создаем DataLoader для обучающей подвыборки
train_dataloader = DataLoader(split_train_, batch_size=BATCH_SIZE,
                              shuffle=True, collate_fn=collate_batch)
# создаем DataLoader для валидационной подвыборки
valid_dataloader = DataLoader(split_valid_, batch_size=BATCH_SIZE,
                              shuffle=True, collate_fn=collate_batch)
# создаем DataLoader для тестовой подвыборки
test_dataloader = DataLoader(test_dataset, batch_size=BATCH_SIZE,
                             shuffle=True, collate_fn=collate_batch)

In [42]:
import time
import mlflow
import mlflow.pytorch
from torch.utils.data.dataset import random_split
from torchtext.data.functional import to_map_style_dataset

with mlflow.start_run(run_name="Text_Classifier_SGD"):

    EPOCHS = 10
    LR = 0.1

    criterion = torch.nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters(), lr=LR)
    scheduler = torch.optim.lr_scheduler.StepLR(optimizer, 1.0, gamma=0.1)

    total_accu = None
    valid_accuracies = []

    mlflow.log_param("epochs", EPOCHS)
    mlflow.log_param("initial_lr", LR)
    mlflow.log_param("optimizer_type", "SGD")
    mlflow.log_param("scheduler_type", "StepLR")
    mlflow.log_param("scheduler_gamma", 0.1)

    for epoch in range(1, EPOCHS + 1):
        epoch_start_time = time.time()

        train(train_dataloader, epoch, optimizer, criterion)

        accu_val = evaluate(valid_dataloader, criterion)
        valid_accuracies.append(accu_val)

        current_lr = optimizer.param_groups[0]["lr"]

        mlflow.log_metric("valid_accuracy", accu_val, step=epoch)
        mlflow.log_metric("learning_rate", current_lr, step=epoch)

        if total_accu is not None and total_accu > accu_val:
            scheduler.step()
        else:
            total_accu = accu_val

        print("-" * 59)
        print(
            "| end of epoch {:3d} | time: {:5.2f}s | "
            "valid accuracy {:8.3f} ".format(
                epoch, time.time() - epoch_start_time, accu_val
            )
        )
        print("-" * 59)

    mlflow.pytorch.log_model(model, artifact_path="text_classifier_model")

[transformers] Disabling PyTorch because PyTorch >= 2.4 is required but found 2.2.2
[transformers] PyTorch was not found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

| epoch   1 |   100/ 2188 batches | accuracy    0.509
| epoch   1 |   200/ 2188 batches | accuracy    0.523
| epoch   1 |   300/ 2188 batches | accuracy    0.520
| epoch   1 |   400/ 2188 batches | accuracy    0.531
| epoch   1 |   500/ 2188 batches | accuracy    0.520
| epoch   1 |   600/ 2188 batches | accuracy    0.526
| epoch   1 |   700/ 2188 batches | accuracy    0.525
| epoch   1 |   800/ 2188 batches | accuracy    0.524
| epoch   1 |   900/ 2188 batches | accuracy    0.524
| epoch   1 |  1000/ 2188 batches | accuracy    0.525
| epoch   1 |  1100/ 2188 batches | accuracy    0.534
| epoch   1 |  1200/ 2188 batches | accuracy    0.540
| epoch   1 |  1300/ 2188 batches | accuracy    0.544
| epoch   1 |  1400/ 2188 batches | accuracy    0.544
| epoch   1 |  1500/ 2188 batches | accuracy    0.532
| epoch   1 |  1600/ 2188 batches | accuracy    0.551
| epoch   1 |  1700/ 2188 batches | accuracy    0.541
| epoch   1 |  1800/ 2188 batches | accuracy    0.530
| epoch   1 |  1900/ 2188 batches | accuracy    0.542
| epoch   1 |  2000/ 2188 batches | accuracy    0.547
| epoch   1 |  2100/ 2188 batches | accuracy    0.564
-----------------------------------------------------------
| end of epoch   1 | time: 581.69s | valid accuracy    0.571
-----------------------------------------------------------
| epoch   2 |   100/ 2188 batches | accuracy    0.553
| epoch   2 |   200/ 2188 batches | accuracy    0.550
| epoch   2 |   300/ 2188 batches | accuracy    0.554
| epoch   2 |   400/ 2188 batches | accuracy    0.545
| epoch   2 |   500/ 2188 batches | accuracy    0.559
| epoch   2 |   600/ 2188 batches | accuracy    0.552
| epoch   2 |   700/ 2188 batches | accuracy    0.546
| epoch   2 |   800/ 2188 batches | accuracy    0.553
| epoch   2 |   900/ 2188 batches | accuracy    0.555
| epoch   2 |  1000/ 2188 batches | accuracy    0.555
| epoch   2 |  1100/ 2188 batches | accuracy    0.557
| epoch   2 |  1200/ 2188 batches | accuracy    0.562
| epoch   2 |  1300/ 2188 batches | accuracy    0.554
| epoch   2 |  1400/ 2188 batches | accuracy    0.565
| epoch   2 |  1500/ 2188 batches | accuracy    0.558
| epoch   2 |  1600/ 2188 batches | accuracy    0.561
| epoch   2 |  1700/ 2188 batches | accuracy    0.561
| epoch   2 |  1800/ 2188 batches | accuracy    0.559
| epoch   2 |  1900/ 2188 batches | accuracy    0.569
| epoch   2 |  2000/ 2188 batches | accuracy    0.566
| epoch   2 |  2100/ 2188 batches | accuracy    0.560
-----------------------------------------------------------
| end of epoch   2 | time: 578.66s | valid accuracy    0.584
-----------------------------------------------------------
| epoch   3 |   100/ 2188 batches | accuracy    0.563
| epoch   3 |   200/ 2188 batches | accuracy    0.569
| epoch   3 |   300/ 2188 batches | accuracy    0.575
| epoch   3 |   400/ 2188 batches | accuracy    0.556
| epoch   3 |   500/ 2188 batches | accuracy    0.574
| epoch   3 |   600/ 2188 batches | accuracy    0.558
| epoch   3 |   700/ 2188 batches | accuracy    0.566
| epoch   3 |   800/ 2188 batches | accuracy    0.576
| epoch   3 |   900/ 2188 batches | accuracy    0.565
| epoch   3 |  1000/ 2188 batches | accuracy    0.565
| epoch   3 |  1100/ 2188 batches | accuracy    0.563
| epoch   3 |  1200/ 2188 batches | accuracy    0.571
| epoch   3 |  1300/ 2188 batches | accuracy    0.572
| epoch   3 |  1400/ 2188 batches | accuracy    0.575
| epoch   3 |  1500/ 2188 batches | accuracy    0.575
| epoch   3 |  1600/ 2188 batches | accuracy    0.570
| epoch   3 |  1700/ 2188 batches | accuracy    0.570
| epoch   3 |  1800/ 2188 batches | accuracy    0.573
| epoch   3 |  1900/ 2188 batches | accuracy    0.574
| epoch   3 |  2000/ 2188 batches | accuracy    0.569
| epoch   3 |  2100/ 2188 batches | accuracy    0.583
-----------------------------------------------------------
| end of epoch   3 | time: 586.23s | valid accuracy    0.599
-----------------------------------------------------------
| epoch   4 |   100/ 2188 batches | accuracy    0.574
| epoch   4 |   200/ 2188 batches | accuracy    0.578
| epoch   4 |   300/ 2188 batches | accuracy    0.575
| epoch   4 |   400/ 2188 batches | accuracy    0.580
| epoch   4 |   500/ 2188 batches | accuracy    0.574
| epoch   4 |   600/ 2188 batches | accuracy    0.581
| epoch   4 |   700/ 2188 batches | accuracy    0.581
| epoch   4 |   800/ 2188 batches | accuracy    0.577
| epoch   4 |   900/ 2188 batches | accuracy    0.587
| epoch   4 |  1000/ 2188 batches | accuracy    0.587
| epoch   4 |  1100/ 2188 batches | accuracy    0.570
| epoch   4 |  1200/ 2188 batches | accuracy    0.591
| epoch   4 |  1300/ 2188 batches | accuracy    0.583
| epoch   4 |  1400/ 2188 batches | accuracy    0.587
| epoch   4 |  1500/ 2188 batches | accuracy    0.589
| epoch   4 |  1600/ 2188 batches | accuracy    0.584
| epoch   4 |  1700/ 2188 batches | accuracy    0.586
| epoch   4 |  1800/ 2188 batches | accuracy    0.580
| epoch   4 |  1900/ 2188 batches | accuracy    0.589
| epoch   4 |  2000/ 2188 batches | accuracy    0.586
| epoch   4 |  2100/ 2188 batches | accuracy    0.581
-----------------------------------------------------------
| end of epoch   4 | time: 619.50s | valid accuracy    0.609
-----------------------------------------------------------
| epoch   5 |   100/ 2188 batches | accuracy    0.579
| epoch   5 |   200/ 2188 batches | accuracy    0.586
| epoch   5 |   300/ 2188 batches | accuracy    0.584
| epoch   5 |   400/ 2188 batches | accuracy    0.584
| epoch   5 |   500/ 2188 batches | accuracy    0.585
| epoch   5 |   600/ 2188 batches | accuracy    0.584
| epoch   5 |   700/ 2188 batches | accuracy    0.589
| epoch   5 |   800/ 2188 batches | accuracy    0.596
| epoch   5 |   900/ 2188 batches | accuracy    0.586
| epoch   5 |  1000/ 2188 batches | accuracy    0.596
| epoch   5 |  1100/ 2188 batches | accuracy    0.593
| epoch   5 |  1200/ 2188 batches | accuracy    0.592
| epoch   5 |  1300/ 2188 batches | accuracy    0.586
| epoch   5 |  1400/ 2188 batches | accuracy    0.592
| epoch   5 |  1500/ 2188 batches | accuracy    0.586
| epoch   5 |  1600/ 2188 batches | accuracy    0.580
| epoch   5 |  1700/ 2188 batches | accuracy    0.588
| epoch   5 |  1800/ 2188 batches | accuracy    0.589
| epoch   5 |  1900/ 2188 batches | accuracy    0.593
| epoch   5 |  2000/ 2188 batches | accuracy    0.589
| epoch   5 |  2100/ 2188 batches | accuracy    0.593
-----------------------------------------------------------
| end of epoch   5 | time: 565.18s | valid accuracy    0.619
-----------------------------------------------------------
| epoch   6 |   100/ 2188 batches | accuracy    0.590
| epoch   6 |   200/ 2188 batches | accuracy    0.588
| epoch   6 |   300/ 2188 batches | accuracy    0.589
| epoch   6 |   400/ 2188 batches | accuracy    0.601
| epoch   6 |   500/ 2188 batches | accuracy    0.586
| epoch   6 |   600/ 2188 batches | accuracy    0.595
| epoch   6 |   700/ 2188 batches | accuracy    0.589
| epoch   6 |   800/ 2188 batches | accuracy    0.592
| epoch   6 |   900/ 2188 batches | accuracy    0.598
| epoch   6 |  1000/ 2188 batches | accuracy    0.589
| epoch   6 |  1100/ 2188 batches | accuracy    0.597
| epoch   6 |  1200/ 2188 batches | accuracy    0.598
| epoch   6 |  1300/ 2188 batches | accuracy    0.597
| epoch   6 |  1400/ 2188 batches | accuracy    0.600
| epoch   6 |  1500/ 2188 batches | accuracy    0.595
| epoch   6 |  1600/ 2188 batches | accuracy    0.602
| epoch   6 |  1700/ 2188 batches | accuracy    0.603
| epoch   6 |  1800/ 2188 batches | accuracy    0.590
| epoch   6 |  1900/ 2188 batches | accuracy    0.593
| epoch   6 |  2000/ 2188 batches | accuracy    0.600
| epoch   6 |  2100/ 2188 batches | accuracy    0.596
-----------------------------------------------------------
| end of epoch   6 | time: 562.95s | valid accuracy    0.622
-----------------------------------------------------------
| epoch   7 |   100/ 2188 batches | accuracy    0.589
| epoch   7 |   200/ 2188 batches | accuracy    0.595
| epoch   7 |   300/ 2188 batches | accuracy    0.595
| epoch   7 |   400/ 2188 batches | accuracy    0.601
| epoch   7 |   500/ 2188 batches | accuracy    0.598
| epoch   7 |   600/ 2188 batches | accuracy    0.595
| epoch   7 |   700/ 2188 batches | accuracy    0.608
| epoch   7 |   800/ 2188 batches | accuracy    0.596
| epoch   7 |   900/ 2188 batches | accuracy    0.596
| epoch   7 |  1000/ 2188 batches | accuracy    0.591
| epoch   7 |  1100/ 2188 batches | accuracy    0.597
| epoch   7 |  1200/ 2188 batches | accuracy    0.603
| epoch   7 |  1300/ 2188 batches | accuracy    0.595
| epoch   7 |  1400/ 2188 batches | accuracy    0.597
| epoch   7 |  1500/ 2188 batches | accuracy    0.590
| epoch   7 |  1600/ 2188 batches | accuracy    0.604
| epoch   7 |  1700/ 2188 batches | accuracy    0.589
| epoch   7 |  1800/ 2188 batches | accuracy    0.604
| epoch   7 |  1900/ 2188 batches | accuracy    0.603
| epoch   7 |  2000/ 2188 batches | accuracy    0.604
| epoch   7 |  2100/ 2188 batches | accuracy    0.612
-----------------------------------------------------------
| end of epoch   7 | time: 544.44s | valid accuracy    0.625
-----------------------------------------------------------
| epoch   8 |   100/ 2188 batches | accuracy    0.605
| epoch   8 |   200/ 2188 batches | accuracy    0.608
| epoch   8 |   300/ 2188 batches | accuracy    0.599
| epoch   8 |   400/ 2188 batches | accuracy    0.600
| epoch   8 |   500/ 2188 batches | accuracy    0.597
| epoch   8 |   600/ 2188 batches | accuracy    0.601
| epoch   8 |   700/ 2188 batches | accuracy    0.601
| epoch   8 |   800/ 2188 batches | accuracy    0.610
| epoch   8 |   900/ 2188 batches | accuracy    0.604
| epoch   8 |  1000/ 2188 batches | accuracy    0.597
| epoch   8 |  1100/ 2188 batches | accuracy    0.592
| epoch   8 |  1200/ 2188 batches | accuracy    0.611
| epoch   8 |  1300/ 2188 batches | accuracy    0.609
| epoch   8 |  1400/ 2188 batches | accuracy    0.599
| epoch   8 |  1500/ 2188 batches | accuracy    0.602
| epoch   8 |  1600/ 2188 batches | accuracy    0.608
| epoch   8 |  1700/ 2188 batches | accuracy    0.598
| epoch   8 |  1800/ 2188 batches | accuracy    0.593
| epoch   8 |  1900/ 2188 batches | accuracy    0.608
| epoch   8 |  2000/ 2188 batches | accuracy    0.597
| epoch   8 |  2100/ 2188 batches | accuracy    0.609
-----------------------------------------------------------
| end of epoch   8 | time: 564.44s | valid accuracy    0.627
-----------------------------------------------------------
| epoch   9 |   100/ 2188 batches | accuracy    0.607
| epoch   9 |   200/ 2188 batches | accuracy    0.609
| epoch   9 |   300/ 2188 batches | accuracy    0.620
| epoch   9 |   400/ 2188 batches | accuracy    0.596
| epoch   9 |   500/ 2188 batches | accuracy    0.617
| epoch   9 |   600/ 2188 batches | accuracy    0.601
| epoch   9 |   700/ 2188 batches | accuracy    0.599
| epoch   9 |   800/ 2188 batches | accuracy    0.596
| epoch   9 |   900/ 2188 batches | accuracy    0.605
| epoch   9 |  1000/ 2188 batches | accuracy    0.600
| epoch   9 |  1100/ 2188 batches | accuracy    0.608
| epoch   9 |  1200/ 2188 batches | accuracy    0.595
| epoch   9 |  1300/ 2188 batches | accuracy    0.608
| epoch   9 |  1400/ 2188 batches | accuracy    0.611
| epoch   9 |  1500/ 2188 batches | accuracy    0.614
| epoch   9 |  1600/ 2188 batches | accuracy    0.609
| epoch   9 |  1700/ 2188 batches | accuracy    0.602
| epoch   9 |  1800/ 2188 batches | accuracy    0.617
| epoch   9 |  1900/ 2188 batches | accuracy    0.595
| epoch   9 |  2000/ 2188 batches | accuracy    0.608
| epoch   9 |  2100/ 2188 batches | accuracy    0.606
-----------------------------------------------------------
| end of epoch   9 | time: 596.00s | valid accuracy    0.630
-----------------------------------------------------------
| epoch  10 |   100/ 2188 batches | accuracy    0.597
| epoch  10 |   200/ 2188 batches | accuracy    0.609
| epoch  10 |   300/ 2188 batches | accuracy    0.599
| epoch  10 |   400/ 2188 batches | accuracy    0.610
| epoch  10 |   500/ 2188 batches | accuracy    0.610
| epoch  10 |   600/ 2188 batches | accuracy    0.614
| epoch  10 |   700/ 2188 batches | accuracy    0.605
| epoch  10 |   800/ 2188 batches | accuracy    0.616
| epoch  10 |   900/ 2188 batches | accuracy    0.593
| epoch  10 |  1000/ 2188 batches | accuracy    0.603
| epoch  10 |  1100/ 2188 batches | accuracy    0.606
| epoch  10 |  1200/ 2188 batches | accuracy    0.603
| epoch  10 |  1300/ 2188 batches | accuracy    0.600
| epoch  10 |  1400/ 2188 batches | accuracy    0.623
| epoch  10 |  1500/ 2188 batches | accuracy    0.609
| epoch  10 |  1600/ 2188 batches | accuracy    0.609
| epoch  10 |  1700/ 2188 batches | accuracy    0.603
| epoch  10 |  1800/ 2188 batches | accuracy    0.615
| epoch  10 |  1900/ 2188 batches | accuracy    0.605
| epoch  10 |  2000/ 2188 batches | accuracy    0.610
| epoch  10 |  2100/ 2188 batches | accuracy    0.605

2026/06/15 21:24:27 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.
2026/06/15 21:24:27 WARNING mlflow.pytorch: Saving pytorch model by Pickle or CloudPickle format requires exercising caution because these formats rely on Python's object serialization mechanism, which can execute arbitrary code during deserialization. The recommended safe alternative is to set `serialization_format` to 'pt2' to save the PyTorch model using the safe graph model format.

-----------------------------------------------------------
| end of epoch  10 | time: 601.67s | valid accuracy    0.633
-----------------------------------------------------------